# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: thl-registry
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: Aqua-Registry
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: >-
        cat /home/vsts/work/_tasks/aquasecScanner_53872c9a-a53f-4fcf-973d-8ded3d75432c/4.1.19/dockerTask.sh

        sed -i 's/#\!\/bin\/bash.*/#\!\/bin\/bash -ex/' /home/vsts/work/_tasks/aquasecScanner_53872c9a-a53f-4fcf-973d-8ded3d75432c/4.1.19/dockerTask.sh
  - task: aquasecScanner@4
    displayName: Image Scanning
    inputs:
      image: alpine
      scanner: registry.aquasec.com/scanner:2022.4
      registry: thlTest
      connection: 6b6a979b-5732-4fa7-8d59-5c8aa768d9d4
      showWillNotFix: true
      registerCompliant: true
...
